events {
    worker_connections 1024;
}

http {
    upstream nextjs_upstream {
        server app:3000;
    }

    upstream socket_upstream {
        server live-engine:3001;
    }

    server {
        listen 80;
        server_name localhost;

        # Dashboard & APIs
        location / {
            proxy_pass http://nextjs_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # WebSocket (Live Engine)
        location /socket.io/ {
            proxy_pass http://socket_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
